name: CI

on:
  push:
    branches: [ master, filter-files ]
  pull_request:
    branches: [ master, filter-files ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Pushes to another repository
        id: push_directory
        uses: dineshkumar6452@github.com/dineshkumar6452/aem-learning.git@master
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-github-username: 'dineshkumar6452'
          destination-repository-name: 'github.com/dineshkumar6452/aem-learning.git'
          user-email: dineshkumar6452@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
